/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.exchange;

import domen.Ekvivalenti;
import domen.EkvivalentiRazmena;
import domen.Predmet;
import domen.Razmena;
import domen.Student;
import gui.student.SearchStudent;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.RazmenaKontroler;
import model.EkvivalentiTableModel;
import model.EkvivalentiTableModel2;

/**
 *
 * @author jovana
 */
public class AddExchange extends javax.swing.JFrame {

    Student izabrani;
    int rb;

    /**
     * Creates new form AddExchange
     */
    public AddExchange() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Dodavanje razmene studenata");

        txtStudent.setEditable(false);
        rbZimski.setSelected(true);
        tblEkvivalenti.setModel(new EkvivalentiTableModel2());
        rb = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnIzaberi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStudent = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEkvivalenti = new javax.swing.JTable();
        btnDodajPredmete = new javax.swing.JButton();
        btnObrisiPredmete = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        rbLetnji = new javax.swing.JRadioButton();
        rbZimski = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSkolskaGodina = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodavanje razmene studenata"));

        btnIzaberi.setText("Izaberi studenta");
        btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiActionPerformed(evt);
            }
        });

        jLabel1.setText("Biranje studenta");

        txtStudent.setText("Izaberite studenta!");

        tblEkvivalenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEkvivalenti);

        btnDodajPredmete.setText("Dodaj predmete");
        btnDodajPredmete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPredmeteActionPerformed(evt);
            }
        });

        btnObrisiPredmete.setText("Obrisi predmete");
        btnObrisiPredmete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPredmeteActionPerformed(evt);
            }
        });

        btnDodaj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDodaj.setText("Dodaj razmenu");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbLetnji);
        rbLetnji.setText("letnji");

        buttonGroup1.add(rbZimski);
        rbZimski.setText("zimski");

        jLabel2.setText("Semestar:");

        jLabel3.setText("Školska godina:");

        txtSkolskaGodina.setText("2023/2024");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtStudent)
                                .addGap(32, 32, 32)
                                .addComponent(btnIzaberi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(rbZimski, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbLetnji, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSkolskaGodina, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnDodajPredmete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnObrisiPredmete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzaberi))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLetnji)
                    .addComponent(rbZimski)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtSkolskaGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajPredmete)
                    .addComponent(btnObrisiPredmete))
                .addGap(38, 38, 38)
                .addComponent(btnDodaj)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiActionPerformed
        new ChooseStudent(this, true).setVisible(true);
    }//GEN-LAST:event_btnIzaberiActionPerformed

    private void btnDodajPredmeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPredmeteActionPerformed
        if (!proveriSemestar()) {
            JOptionPane.showMessageDialog(null, "Ne možete promeniti semestar ako su neki predmeti već dodati.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new ChooseSubjects(this, true, rbZimski.isSelected()).setVisible(true);
    }//GEN-LAST:event_btnDodajPredmeteActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        //int studentId = izabrani.getId();
        EkvivalentiTableModel2 etb = (EkvivalentiTableModel2) tblEkvivalenti.getModel();
        //List<Ekvivalenti> listaEkvivalenata = etb.getLista();
        String skolskaGodina = txtSkolskaGodina.getText();
        String semestar = rbZimski.isSelected() ? "Zimski" : "Letnji";
        List<EkvivalentiRazmena> listaEkvNaRazmeni = etb.getLista();
        for (EkvivalentiRazmena ekvivalentiRazmena : listaEkvNaRazmeni) {
            System.out.println(ekvivalentiRazmena.getEkvivalenti().getPredmetFon() + " " + ekvivalentiRazmena.getEkvivalenti().getPredmetDrugiFakultet());
        }

        Razmena razmena = new Razmena(0, izabrani, semestar, skolskaGodina, listaEkvNaRazmeni);
        if (RazmenaKontroler.getInstance().dodajRazmenu(razmena)) {
            JOptionPane.showMessageDialog(this, "Sistem je dodao razmenu", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            //dialog.popuniTabelu(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da doda razmenu", "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiPredmeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPredmeteActionPerformed
        int row = tblEkvivalenti.getSelectedRow();
        if (row != -1) {
            EkvivalentiTableModel2 etb = (EkvivalentiTableModel2) tblEkvivalenti.getModel();
            etb.obrisiEkvivalente(row);
            rb--;
        }
    }//GEN-LAST:event_btnObrisiPredmeteActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddExchange().setVisible(true);
//            }
//        });
//    }
    public void postaviIzabranogStudenta(Student student) {
        izabrani = student;
        txtStudent.setText(izabrani.toString());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajPredmete;
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JButton btnObrisiPredmete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLetnji;
    private javax.swing.JRadioButton rbZimski;
    private javax.swing.JTable tblEkvivalenti;
    private javax.swing.JTextField txtSkolskaGodina;
    private javax.swing.JTextField txtStudent;
    // End of variables declaration//GEN-END:variables

    void dodajPredmete(Predmet p1, Predmet p2) {
        Ekvivalenti e = new Ekvivalenti(0, p1, p2, 2024);
        EkvivalentiTableModel etb = (EkvivalentiTableModel) tblEkvivalenti.getModel();
        etb.dodajRed(e);
    }

    private boolean proveriSemestar() {
        EkvivalentiTableModel2 etb = (EkvivalentiTableModel2) tblEkvivalenti.getModel();
        if (etb.getLista().isEmpty()) {
            return true;
        }
        String semestar = rbZimski.isSelected() ? "Zimski" : "Letnji";

        return etb.getLista().getLast().getEkvivalenti().getPredmetDrugiFakultet().getSemestar().equals(semestar);
    }

    void dodajEkvivalente(Ekvivalenti e) {
        EkvivalentiTableModel2 etb = (EkvivalentiTableModel2) tblEkvivalenti.getModel();
        EkvivalentiRazmena e2 = new EkvivalentiRazmena(++rb, null, e, 0);
        etb.dodajRed(e2);
    }
}
