/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.exchange;

import java.time.Year;
import domen.Ekvivalenti;
import domen.EkvivalentiRazmena;
import domen.Predmet;
import domen.Razmena;
import domen.Student;
import domen.Univerzitet;
import gui.student.SearchStudent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import kontroler.RazmenaKontroler;
import kontroler.UniverzitetKontroler;
import model.EkvivalentiTableModel;

/**
 *
 * @author jovana
 */
public class AddExchange extends javax.swing.JFrame {

    Student izabraniStudent;
    Univerzitet izabraniUniverzitet;
    Univerzitet fon;
    int rb;

    /**
     * Creates new form AddExchange
     */
    public AddExchange() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Dodavanje razmene studenata");

        txtStudent.setEditable(false);
        rbZimski.setSelected(true);
        popuniUniverzitete();
        tblEkvivalenti.setModel(new EkvivalentiTableModel());
        TableColumn firstColumn = tblEkvivalenti.getColumnModel().getColumn(0);
        firstColumn.setMinWidth(50);
        firstColumn.setMaxWidth(50);
        firstColumn.setPreferredWidth(50);
        rb = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnIzaberiStudenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStudent = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEkvivalenti = new javax.swing.JTable();
        btnDodajPredmete = new javax.swing.JButton();
        btnObrisiPredmete = new javax.swing.JButton();
        rbLetnji = new javax.swing.JRadioButton();
        rbZimski = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSkolskaGodina = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbUniverziteti = new javax.swing.JComboBox();
        btnDodajRazmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos podataka o razmeni"));

        btnIzaberiStudenta.setText("Izaberite studenta");
        btnIzaberiStudenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiStudentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Biranje studenta");

        txtStudent.setText("Izaberite studenta!");

        tblEkvivalenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEkvivalenti);

        btnDodajPredmete.setText("Dodaj predmete");
        btnDodajPredmete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPredmeteActionPerformed(evt);
            }
        });

        btnObrisiPredmete.setText("Obrisi predmete");
        btnObrisiPredmete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPredmeteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbLetnji);
        rbLetnji.setText("letnji");

        buttonGroup1.add(rbZimski);
        rbZimski.setText("zimski");

        jLabel2.setText("Semestar:");

        jLabel3.setText("Školska godina:");

        txtSkolskaGodina.setText("2023/2024");

        jLabel4.setText("Biranje univerziteta:");

        cmbUniverziteti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(rbZimski, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbLetnji, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSkolskaGodina, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(294, 294, 294))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbUniverziteti, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStudent))
                        .addGap(18, 18, 18)
                        .addComponent(btnIzaberiStudenta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnDodajPredmete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(btnObrisiPredmete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzaberiStudenta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLetnji)
                    .addComponent(rbZimski)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtSkolskaGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cmbUniverziteti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiPredmete)
                    .addComponent(btnDodajPredmete))
                .addContainerGap())
        );

        btnDodajRazmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDodajRazmenu.setText("Dodaj razmenu");
        btnDodajRazmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajRazmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(btnDodajRazmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDodajRazmenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzaberiStudentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiStudentaActionPerformed
        new ChooseStudent(this, true).setVisible(true);
    }//GEN-LAST:event_btnIzaberiStudentaActionPerformed

    private void btnDodajPredmeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPredmeteActionPerformed
        if (!proveriSemestar()) {
            JOptionPane.showMessageDialog(null, "Ne možete promeniti semestar ako su neki predmeti već dodati.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!proveriUniverzitet()) {
            JOptionPane.showMessageDialog(null, "Ne možete promeniti univerzitet ako su neki predmeti već dodati.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Univerzitet u = (Univerzitet) cmbUniverziteti.getSelectedItem();
        new ChooseSubjects(this, true, rbZimski.isSelected(), u ).setVisible(true);
    }//GEN-LAST:event_btnDodajPredmeteActionPerformed

    private void btnDodajRazmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajRazmenuActionPerformed
        //int studentId = izabraniStudent.getId();
        //List<Ekvivalenti> listaEkvivalenata = etb.getLista();

        if (izabraniStudent == null) {
            JOptionPane.showMessageDialog(this, "Morate izabrati studenta.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.izabraniUniverzitet= (Univerzitet) cmbUniverziteti.getSelectedItem();
        if(!proveriUniverzitet()){
            JOptionPane.showMessageDialog(this, "Ne smete promeniti univerzitet.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (izabraniUniverzitet == null) {
            JOptionPane.showMessageDialog(this, "Morate izabrati univerzitet.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String skolskaGodina = txtSkolskaGodina.getText();
        if (!isValidSkolskaGodina(skolskaGodina)) {
            JOptionPane.showMessageDialog(this, "Skolska godina mora da bude u odgovarajucem formatu.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        EkvivalentiTableModel etb = (EkvivalentiTableModel) tblEkvivalenti.getModel();
        List<EkvivalentiRazmena> listaEkvNaRazmeni = etb.getLista();
        if (listaEkvNaRazmeni.size() < 3) {
            JOptionPane.showMessageDialog(this, "Razmena mora da ima bar 3 predmeta.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (EkvivalentiRazmena ekvivalentiRazmena : listaEkvNaRazmeni) {
            System.out.println(ekvivalentiRazmena.getEkvivalenti().getPredmetFon() + " " + ekvivalentiRazmena.getEkvivalenti().getPredmetDrugiFakultet());
        }
        String semestar = rbZimski.isSelected() ? "Zimski" : "Letnji";

        this.izabraniUniverzitet = (Univerzitet) cmbUniverziteti.getSelectedItem();
        Razmena razmena = new Razmena(0, izabraniStudent, semestar, skolskaGodina, fon, izabraniUniverzitet, listaEkvNaRazmeni);
        if (RazmenaKontroler.getInstance().dodajRazmenu(razmena)) {
            JOptionPane.showMessageDialog(this, "Sistem je dodao razmenu", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            //dialog.popuniTabelu(null);
            //this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da doda razmenu", "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDodajRazmenuActionPerformed

    private void btnObrisiPredmeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPredmeteActionPerformed
        int row = tblEkvivalenti.getSelectedRow();
        if (row != -1) {
            EkvivalentiTableModel etb = (EkvivalentiTableModel) tblEkvivalenti.getModel();
            etb.obrisiEkvivalente(row);
            rb--;
            etb.resetujRB();

        }
    }//GEN-LAST:event_btnObrisiPredmeteActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddExchange().setVisible(true);
//            }
//        });
//    }
    public void postaviIzabranogStudenta(Student student) {
        izabraniStudent = student;
        txtStudent.setText(izabraniStudent.toString());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajPredmete;
    private javax.swing.JButton btnDodajRazmenu;
    private javax.swing.JButton btnIzaberiStudenta;
    private javax.swing.JButton btnObrisiPredmete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbUniverziteti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLetnji;
    private javax.swing.JRadioButton rbZimski;
    private javax.swing.JTable tblEkvivalenti;
    private javax.swing.JTextField txtSkolskaGodina;
    private javax.swing.JTextField txtStudent;
    // End of variables declaration//GEN-END:variables

//    void dodajPredmete(Predmet p1, Predmet p2) {
//        Ekvivalenti e = new Ekvivalenti(0, p1, p2, 2024);
//        EkvivalentiTableModel_NE_KORISTIM etb = (EkvivalentiTableModel_NE_KORISTIM) tblEkvivalenti.getModel();
//        etb.dodajRed(e);
//    }
    private boolean proveriSemestar() {
        EkvivalentiTableModel etb = (EkvivalentiTableModel) tblEkvivalenti.getModel();
        if (etb.getLista().isEmpty()) {
            return true;
        }
        String semestar = rbZimski.isSelected() ? "Zimski" : "Letnji";

        return etb.getLista().getLast().getEkvivalenti().getPredmetDrugiFakultet().getSemestar().equals(semestar);
    }

    private void popuniUniverzitete() {
        List<Univerzitet> listaUniverziteta = UniverzitetKontroler.getInstance().ucitajListuUniverziteta();
        cmbUniverziteti.removeAllItems();
        for (Univerzitet u : listaUniverziteta) {
            if (u.getNaziv().equals("Fakultet Organizacionih Nauka")) {
                this.fon = u;
            } else {
                cmbUniverziteti.addItem(u);
            }
        }
    }

    void dodajEkvivalente(Ekvivalenti e) {
        EkvivalentiTableModel etb = (EkvivalentiTableModel) tblEkvivalenti.getModel();
        EkvivalentiRazmena e2 = new EkvivalentiRazmena(++rb, null, e, 0);
        etb.dodajRed(e2);
        etb.resetujRB();
    }

    private boolean proveriUniverzitet() {
        EkvivalentiTableModel etb = (EkvivalentiTableModel) tblEkvivalenti.getModel();
        if (etb.getLista().isEmpty()) {
            return true;
        }
        Univerzitet u = (Univerzitet) cmbUniverziteti.getSelectedItem();

        return etb.getLista().getLast().getEkvivalenti().getPredmetDrugiFakultet().getUniverzitet().equals(u);
    }

    public boolean isValidSkolskaGodina(String skolskaGodina) {
        // Regex za format "godina/godina"
        String regex = "^(20\\d{2})/(20\\d{2})$";

        // Proveri da li uneti string odgovara regexu
        if (skolskaGodina.matches(regex)) {
            // Dobij trenutnu godinu
            int currentYear = Year.now().getValue();

            // Podeli string na dve godine
            String[] godine = skolskaGodina.split("/");
            int prvaGodina = Integer.parseInt(godine[0]);
            int drugaGodina = Integer.parseInt(godine[1]);

            // Proveri da li su godine u validnom opsegu i da li je razlika između njih tačno 1
            if (prvaGodina >= 2000 && drugaGodina <= currentYear && drugaGodina - prvaGodina == 1) {
                return true;
            }
        }

        return false;
    }

}
