/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.exchange;

import domen.Ekvivalenti;
import domen.EkvivalentiRazmena;
import domen.Razmena;
import domen.Student;
import java.time.Year;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import kontroler.RazmenaKontroler;
import model.EkvivalentiTableModel;

/**
 *
 * @author jovana
 */
public class UpdateExchange extends javax.swing.JFrame {

    Student izabrani;
    int rb;
    SearchExchange parent;
    int razmenaID;
    Razmena izabranaRazmena;

    /**
     * Creates new form UpdateExchange
     */
    public UpdateExchange(SearchExchange parent, Razmena razmena) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ažuriranje razmene");

        this.parent = parent;
        txtStudent.setEditable(false);
        tblEkvivalenti.setModel(new EkvivalentiTableModel(razmena.getListaEkvivalenata()));
        TableColumn firstColumn = tblEkvivalenti.getColumnModel().getColumn(0);
        firstColumn.setMinWidth(50);
        firstColumn.setMaxWidth(50);
        firstColumn.setPreferredWidth(50);
        razmenaID = razmena.getRazmenaID();
        rb = razmena.getListaEkvivalenata().size();
        this.izabranaRazmena = razmena;

        popuniPolja(razmena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPromeni = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSkolskaGodina = new javax.swing.JTextField();
        txtStudent = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEkvivalenti = new javax.swing.JTable();
        btnDodajPredmete = new javax.swing.JButton();
        btnObrisiPredmete = new javax.swing.JButton();
        rbLetnji = new javax.swing.JRadioButton();
        rbZimski = new javax.swing.JRadioButton();
        btnAzuriraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Izmena podataka o razmeni"));

        jLabel2.setText("Semestar:");

        btnPromeni.setText("Promeni studenta");
        btnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniActionPerformed(evt);
            }
        });

        jLabel3.setText("Školska godina:");

        jLabel1.setText("Student:");

        txtSkolskaGodina.setText("2023/2024");

        txtStudent.setText("Izaberite studenta!");

        tblEkvivalenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEkvivalenti);

        btnDodajPredmete.setText("Dodaj predmete");
        btnDodajPredmete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPredmeteActionPerformed(evt);
            }
        });

        btnObrisiPredmete.setText("Obrisi predmete");
        btnObrisiPredmete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPredmeteActionPerformed(evt);
            }
        });

        rbLetnji.setText("letnji");

        rbZimski.setText("zimski");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtStudent)
                                .addGap(32, 32, 32)
                                .addComponent(btnPromeni))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel2)
                                        .addGap(24, 24, 24)
                                        .addComponent(rbZimski, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbLetnji, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSkolskaGodina, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(btnDodajPredmete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(btnObrisiPredmete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPromeni))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLetnji)
                    .addComponent(rbZimski)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtSkolskaGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajPredmete)
                    .addComponent(btnObrisiPredmete))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        btnAzuriraj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAzuriraj.setText("Ažuriraj razmenu");
        btnAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(btnAzuriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAzuriraj)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        new ChooseStudent(this, true).setVisible(true);
    }//GEN-LAST:event_btnPromeniActionPerformed

    private void btnDodajPredmeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPredmeteActionPerformed
        if (!proveriSemestar()) {
            JOptionPane.showMessageDialog(null, "Ne možete promeniti semestar ako su neki predmeti već dodati.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new ChooseSubjects(this, true, rbZimski.isSelected()).setVisible(true);
    }//GEN-LAST:event_btnDodajPredmeteActionPerformed

    private void btnObrisiPredmeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPredmeteActionPerformed
        int row = tblEkvivalenti.getSelectedRow();
        if (row != -1) {
            EkvivalentiTableModel etb = (EkvivalentiTableModel) tblEkvivalenti.getModel();
            etb.obrisiEkvivalente(row);
            etb.resetujRB();
        }
    }//GEN-LAST:event_btnObrisiPredmeteActionPerformed

    private void btnAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajActionPerformed
        //int studentId = izabrani.getId();
        //List<Ekvivalenti> listaEkvivalenata = etb.getLista();
        String skolskaGodina = txtSkolskaGodina.getText();
        if (!isValidSkolskaGodina(skolskaGodina)) {
            JOptionPane.showMessageDialog(this, "Skolska godina mora da bude u odgovarajucem formatu.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String semestar = rbZimski.isSelected() ? "Zimski" : "Letnji";

        EkvivalentiTableModel etb = (EkvivalentiTableModel) tblEkvivalenti.getModel();
        List<EkvivalentiRazmena> listaEkvNaRazmeni = etb.getLista();
        if (listaEkvNaRazmeni.size() < 3) {
            JOptionPane.showMessageDialog(this, "Razmena mora da ima bar 3 predmeta.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (EkvivalentiRazmena ekvivalentiRazmena : listaEkvNaRazmeni) {
            System.out.println(ekvivalentiRazmena.getEkvivalenti().getPredmetFon() + " " + ekvivalentiRazmena.getEkvivalenti().getPredmetDrugiFakultet());
        }

        Razmena razmena = new Razmena(razmenaID, izabrani, semestar, skolskaGodina, listaEkvNaRazmeni);

        if (RazmenaKontroler.getInstance().azurirajRazmenu(razmena)) {
            JOptionPane.showMessageDialog(this, "Sistem je azurirao razmenu", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            //dialog.popuniTabelu(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da azurira razmenu", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAzurirajActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpdateExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpdateExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpdateExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpdateExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UpdateExchange().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzuriraj;
    private javax.swing.JButton btnDodajPredmete;
    private javax.swing.JButton btnObrisiPredmete;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLetnji;
    private javax.swing.JRadioButton rbZimski;
    private javax.swing.JTable tblEkvivalenti;
    private javax.swing.JTextField txtSkolskaGodina;
    private javax.swing.JTextField txtStudent;
    // End of variables declaration//GEN-END:variables

    private boolean proveriSemestar() {
        EkvivalentiTableModel etb = (EkvivalentiTableModel) tblEkvivalenti.getModel();
        if (etb.getLista().isEmpty()) {
            return true;
        }
        String semestar = rbZimski.isSelected() ? "Zimski" : "Letnji";

        return etb.getLista().getLast().getEkvivalenti().getPredmetDrugiFakultet().getSemestar().equals(semestar);
    }

    private void popuniPolja(Razmena razmena) {
        txtSkolskaGodina.setText(razmena.getSkolskaGodina());
        txtStudent.setText(razmena.getStudent().toString());
        izabrani = razmena.getStudent();
        rbZimski.setSelected(razmena.getSemestar().equals("Zimski"));
        //popuniTabelu(razmena.getListaEkvivalenata());

    }

//    private void popuniTabelu(List<EkvivalentiRazmena> listaEkvivalenata) {
//        EkvivalentiTableModel etm = (EkvivalentiTableModel) tblEkvivalenti.getModel();
//        etm.setLista(listaEkvivalenata);
//    }
    void dodajEkvivalente(Ekvivalenti e) {
        EkvivalentiTableModel etb = (EkvivalentiTableModel) tblEkvivalenti.getModel();
        EkvivalentiRazmena e2 = new EkvivalentiRazmena(++rb, izabranaRazmena, e, 0);
        etb.dodajRed(e2);
        etb.resetujRB();

    }

    public boolean isValidSkolskaGodina(String skolskaGodina) {
        // Regex za format "godina/godina"
        String regex = "^(20\\d{2})/(20\\d{2})$";

        // Proveri da li uneti string odgovara regexu
        if (skolskaGodina.matches(regex)) {
            // Dobij trenutnu godinu
            int currentYear = Year.now().getValue();

            // Podeli string na dve godine
            String[] godine = skolskaGodina.split("/");
            int prvaGodina = Integer.parseInt(godine[0]);
            int drugaGodina = Integer.parseInt(godine[1]);

            // Proveri da li su godine u validnom opsegu i da li je razlika između njih tačno 1
            if (prvaGodina >= 2000 && drugaGodina <= currentYear && drugaGodina - prvaGodina == 1) {
                return true;
            }
        }

        return false;
    }
}
